meta_product_name: "Noted"
meta_type: "Music"
meta_url: "https://noted.digital/"
meta_title: "Noted - A platform to bring people together over the love of music"
meta_description: "A platform for music lovers to share there ideas and connect people to good music"
meta_image: "note.png" # should exist in `app/assets/images/`
